name: Staging - Deploy External Site

on:
  push:
    branches:
      - develop

jobs:
  build_deploy_services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          node --version
          npm --version
      - name: Building External Site
        run: |
          npm install
          npm run build-staging
      - name: Deploy External Site to Staging S3
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID_DEV }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}"
          AWS_REGION: us-west-2
        run: |
          export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          aws configure set preview.cloudfront true
          aws s3 sync build/ s3://altitude-staging-external-site
      - name: Create a CloudFront Invalidation
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID_DEV }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}"
          AWS_REGION: us-west-2
        run: |
          export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          aws cloudfront create-invalidation --distribution-id E3CF7CJEBPKT47 --paths "/*"  --output text