const STATE_DESCRIPTIONS = {
  FILE: 'File',
  COMPANY_OWNED: 'Company Owned',
  COMPANY_OWNED_NEGATIVE: 'Externally Owned',
  SENSITIVE: 'Potentially Sensitive File',
  MOST_SHARED: 'Most Shared Files',
  MOST_SHARED_SHORT: 'Most Shared',
  MANY_DOWNLOADS_SHORT: 'Many Recent Downloads',
  MANY_DOWNLOADS: 'Many Files Downloaded in 24 hours',
  DOWNLOADS_BY_APP: 'by Authorized App',
  DOWNLOADS_BY_APP_SHORT: 'by App',
  INTERNAL_LINK_SHARE: 'Shared by Link Internally',
  EXTERNAL_LINK_SHARE: 'Shared by Link Externally',
  PERSONAL_SHARE: 'Shared to Personal Email Account',
  PERSONAL_SHARE_SHORT: 'Shared to Personal',
  INTERNAL_ACCOUNT: 'Internal Account',
  EXTERNAL_ACCOUNT: 'External Account',
  OLD_RISK: 'Created Over 180 Days Ago',
  INTERNAL_LINK: 'Internal Link',
  EXTERNAL_LINK: 'External Link',
  SESNITIVE_TAG: '(sensitive)',
  COMPANY_OWNED_NEGATIVE_TAG: '(externally owned)',
  SENSITIVE_EXTERNAL_TAG: '(externally owned, sensitive)',
  OLD_TAG: '(6 mo. old)',
  SESNITIVE_OLD_TAG: '(sensitive, 6 mo. old)',
  MOST_ACCESS_FILES: 'Most Accessed Files by Non-Employee'
}

export const HELP_STRINGS = {
  RISK_CATALOG: {
    RISK_0_NAME: `${STATE_DESCRIPTIONS.MOST_SHARED} - ${STATE_DESCRIPTIONS.COMPANY_OWNED}`,
    RISK_0_SHORT: STATE_DESCRIPTIONS.MOST_SHARED_SHORT,
    RISK_0_DESCRIPTION: 'These are files owned by people inside your organization that have been shared the most.',
    RISK_10_NAME: `${STATE_DESCRIPTIONS.MOST_SHARED} - ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE}`,
    RISK_10_SHORT: `${STATE_DESCRIPTIONS.MOST_SHARED_SHORT} ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE_TAG}`,
    RISK_10_DESCRIPTION: 'These are files owned by people outside of your organization that have been shared the most.',
    RISK_11_NAME: `${STATE_DESCRIPTIONS.MOST_ACCESS_FILES}`,
    RISK_11_SHORT: `${STATE_DESCRIPTIONS.MOST_ACCESS_FILES}`,
    RISK_11_DESCRIPTION: 'These are files that have been accessed the most by people outside of your organization.',
    RISK_1011_NAME: `${STATE_DESCRIPTIONS.SENSITIVE} ${STATE_DESCRIPTIONS.INTERNAL_LINK_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED}`,
    RISK_1011_SHORT: `${STATE_DESCRIPTIONS.INTERNAL_LINK} ${STATE_DESCRIPTIONS.SESNITIVE_TAG}`,
    RISK_1011_DESCRIPTION:
      'A sensitive file owned by someone in your organization has been shared by a link within your organization.',
    RISK_1013_NAME: `${STATE_DESCRIPTIONS.SENSITIVE} ${STATE_DESCRIPTIONS.INTERNAL_LINK_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE}`,
    RISK_1013_SHORT: `${STATE_DESCRIPTIONS.INTERNAL_LINK} ${STATE_DESCRIPTIONS.SESNITIVE_TAG} ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE_TAG}`,
    RISK_1013_DESCRIPTION:
      'A sensitive file owned by someone outside of your organization has been shared by link within your organization.',
    RISK_1020_NAME: `${STATE_DESCRIPTIONS.FILE} ${STATE_DESCRIPTIONS.EXTERNAL_LINK_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED}`,
    RISK_1020_SHORT: STATE_DESCRIPTIONS.EXTERNAL_LINK,
    RISK_1020_DESCRIPTION:
      'A file owned by someone in your organization has been shared by a link to someone outside your organization.',
    RISK_1021_NAME: `${STATE_DESCRIPTIONS.SENSITIVE} ${STATE_DESCRIPTIONS.EXTERNAL_LINK_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED}`,
    RISK_1021_SHORT: `${STATE_DESCRIPTIONS.EXTERNAL_LINK} ${STATE_DESCRIPTIONS.SESNITIVE_TAG}`,
    RISK_1021_DESCRIPTION:
      'A sensitive file owned by someone in your organization has been shared by a link to someone outside your organization.',
    RISK_1022_NAME: `${STATE_DESCRIPTIONS.FILE} ${STATE_DESCRIPTIONS.EXTERNAL_LINK_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE}`,
    RISK_1022_SHORT: `${STATE_DESCRIPTIONS.EXTERNAL_LINK} ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE_TAG}`,
    RISK_1022_DESCRIPTION:
      'A file owned by someone outside of your organization has been shared by a link to someone outside your organization.',
    RISK_1023_NAME: `${STATE_DESCRIPTIONS.SENSITIVE} ${STATE_DESCRIPTIONS.EXTERNAL_LINK_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE}`,
    RISK_1023_SHORT: `${STATE_DESCRIPTIONS.EXTERNAL_LINK} ${STATE_DESCRIPTIONS.SENSITIVE_EXTERNAL_TAG}`,
    RISK_1023_DESCRIPTION:
      'A sensitive file owned by someone outside of your organization has been shared by a link to someone outside your organization.',
    RISK_1050_NAME: `${STATE_DESCRIPTIONS.FILE} ${STATE_DESCRIPTIONS.EXTERNAL_LINK_SHARE} - ${STATE_DESCRIPTIONS.OLD_RISK}`,
    RISK_1050_SHORT: `${STATE_DESCRIPTIONS.EXTERNAL_LINK} ${STATE_DESCRIPTIONS.OLD_TAG}`,
    RISK_1051_NAME: `${STATE_DESCRIPTIONS.SENSITIVE} ${STATE_DESCRIPTIONS.EXTERNAL_LINK_SHARE} - ${STATE_DESCRIPTIONS.OLD_RISK}`,
    RISK_1051_SHORT: `${STATE_DESCRIPTIONS.EXTERNAL_LINK} ${STATE_DESCRIPTIONS.SESNITIVE_OLD_TAG}`,
    RISK_2000_NAME: `${STATE_DESCRIPTIONS.FILE} ${STATE_DESCRIPTIONS.PERSONAL_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED}`,
    RISK_2000_SHORT: STATE_DESCRIPTIONS.PERSONAL_SHARE_SHORT,
    RISK_2000_DESCRIPTION: 'A file owned by someone in your organization has been shared to a personal email account.',
    RISK_2001_NAME: `${STATE_DESCRIPTIONS.SENSITIVE} ${STATE_DESCRIPTIONS.PERSONAL_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED}`,
    RISK_2001_SHORT: `${STATE_DESCRIPTIONS.PERSONAL_SHARE_SHORT} ${STATE_DESCRIPTIONS.SESNITIVE_TAG}`,
    RISK_2001_DESCRIPTION:
      'A sensitive file owned by someone in your organization has been shared to a personal email account.',
    RISK_2002_NAME: `${STATE_DESCRIPTIONS.FILE} ${STATE_DESCRIPTIONS.PERSONAL_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE}`,
    RISK_2002_SHORT: `${STATE_DESCRIPTIONS.PERSONAL_SHARE_SHORT} ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE_TAG}`,
    RISK_2002_DESCRIPTION:
      'A file owned by someone outside of your organization has been shared to a personal email account.',
    RISK_2003_NAME: `${STATE_DESCRIPTIONS.SENSITIVE} ${STATE_DESCRIPTIONS.PERSONAL_SHARE} - ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE}`,
    RISK_2003_SHORT: `${STATE_DESCRIPTIONS.PERSONAL_SHARE_SHORT} ${STATE_DESCRIPTIONS.SESNITIVE_TAG} ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE_TAG}`,
    RISK_2003_DESCRIPTION:
      'A sensitive file owned by someone outside of your organization has been shared to a personal email account.',
    RISK_2010_NAME: `${STATE_DESCRIPTIONS.FILE} ${STATE_DESCRIPTIONS.PERSONAL_SHARE} - ${STATE_DESCRIPTIONS.OLD_RISK}`,
    RISK_2010_SHORT: `${STATE_DESCRIPTIONS.PERSONAL_SHARE_SHORT} ${STATE_DESCRIPTIONS.OLD_TAG}`,
    RISK_2011_NAME: `${STATE_DESCRIPTIONS.SENSITIVE} ${STATE_DESCRIPTIONS.PERSONAL_SHARE} - ${STATE_DESCRIPTIONS.OLD_RISK}`,
    RISK_2011_SHORT: `${STATE_DESCRIPTIONS.PERSONAL_SHARE_SHORT} ${STATE_DESCRIPTIONS.SESNITIVE_OLD_TAG}`,
    RISK_3100_NAME: `${STATE_DESCRIPTIONS.MANY_DOWNLOADS} by ${STATE_DESCRIPTIONS.INTERNAL_ACCOUNT}`,
    RISK_3100_SHORT: `${STATE_DESCRIPTIONS.MANY_DOWNLOADS_SHORT} - ${STATE_DESCRIPTIONS.INTERNAL_ACCOUNT}`,
    RISK_3100_DESCRIPTION:
      'A person inside your organization has downloaded more than the set internal threshold in the past 24 hours. The default is 25 files.',
    RISK_3200_NAME: `${STATE_DESCRIPTIONS.MANY_DOWNLOADS} by ${STATE_DESCRIPTIONS.EXTERNAL_ACCOUNT}`,
    RISK_3200_SHORT: `${STATE_DESCRIPTIONS.MANY_DOWNLOADS_SHORT} - ${STATE_DESCRIPTIONS.EXTERNAL_ACCOUNT}`,
    RISK_3200_DESCRIPTION:
      'A person inside your organization has downloaded more than the set external threshold in the past 24 hours. The default is 25 files.',
    RISK_3010_NAME: `${STATE_DESCRIPTIONS.MANY_DOWNLOADS} ${STATE_DESCRIPTIONS.DOWNLOADS_BY_APP} - ${STATE_DESCRIPTIONS.COMPANY_OWNED}`,
    RISK_3010_SHORT: `${STATE_DESCRIPTIONS.MANY_DOWNLOADS_SHORT} ${STATE_DESCRIPTIONS.DOWNLOADS_BY_APP_SHORT}`,
    RISK_3010_DESCRIPTION:
      'An application owned by your organization has downloaded more than the set internal threshold in the past 24 hours. The default is 25 files.',
    RISK_3012_NAME: `${STATE_DESCRIPTIONS.MANY_DOWNLOADS} ${STATE_DESCRIPTIONS.DOWNLOADS_BY_APP} - ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE}`,
    RISK_3012_SHORT: `${STATE_DESCRIPTIONS.MANY_DOWNLOADS_SHORT} ${STATE_DESCRIPTIONS.DOWNLOADS_BY_APP_SHORT} ${STATE_DESCRIPTIONS.COMPANY_OWNED_NEGATIVE_TAG}`,
    RISK_3012_DESCRIPTION:
      'An application owned by a third party has downloaded more than the set external threshold in the past 24 hours. The default is 25 files.'
  }
}
