from inspect import cleandoc as trim
from typing import Any, List

import altitude_db_schema
import pytest
from tools import datetime_tools, json_tools
from tools.retry_backoff_class import RetryAndCatch
from tools.sql import SQLConnect

from external_api.utils.constants import GoogleTableNames, MicrosoftTableNames


@pytest.fixture(scope="session")
def mysql_with_schema(mysql_route):
    sql_connect = SQLConnect(mysql_route)
    with RetryAndCatch.no_retry():
        with sql_connect.open(), sql_connect.transaction():
            for schema_statement in altitude_db_schema.schema_statements():
                sql_connect.execute(schema_statement)
    return mysql_route


@pytest.fixture
def sql_connect(mysql_route):
    sql_connect = SQLConnect(mysql_route)
    with sql_connect.open():
        yield sql_connect


@pytest.helpers.register
def clear_tables(sql_connect: SQLConnect, table_names: List[str]) -> None:
    with sql_connect.transaction():
        for table_name in table_names:
            sql_connect.execute(f"DELETE FROM {table_name}")


@pytest.helpers.register
def insert_into_table(sql_connect: SQLConnect, table_name: str, objects: List[Any]) -> None:
    with sql_connect.transaction():
        for obj in objects:
            columns = obj.keys()
            insert_query = trim(
                f"""
                INSERT INTO {table_name} (
                    {", ".join(columns)}
                )
                VALUES (
                    {", ".join(f"%({column})s" for column in columns)}
                )
                """
            )
            sql_connect.execute(insert_query, obj)


@pytest.fixture
def mysql_connect(mysql_with_schema, table_names):
    mysql_connect = SQLConnect(mysql_with_schema)
    pytest.helpers.clear_tables(mysql_connect, table_names)
    return mysql_connect


@pytest.fixture
def table_names():
    return [table.value for table in GoogleTableNames] + [
        table.value for table in MicrosoftTableNames
    ]


#############################
## GSUITE TABLE FIXTURE DATA
#############################
@pytest.fixture
def admin_directory_v1_usersmeta_data():
    return [
        {
            "id": "100067654994463939381",
            "primaryEmail": "michael@thoughtlabs.io",
            "emails_primary": "mwcoates@gmail.com,mwcoates@thoughtlabs.biz",
            "name_fullname": "Michael Coates",
            "name_givenname": "Michael",
            "name_familyname": "Coates",
        },
        {
            "id": "10068429338294482382",
            "primaryEmail": "nyah@thoughtlabs.io",
            "emails_primary": "nyahc@test.io,neeya@tech.biz,check.nyah@gmail.com,nyah@thoughtlabs.biz",
            "name_fullname": "Nyah Check",
            "name_givenname": "Nyah",
            "name_familyname": "Check",
        },
        {
            "id": "482344844948343829",
            "primaryEmail": "bobbie@thoughtlabs.io",
            "emails_primary": "bobbie@thoughtlabs.biz,bobbieh@gmail.com",
            "name_fullname": "Bobbie Hawaii",
            "name_givenname": "Bobbie",
            "name_familyname": "Hawaii",
        },
        {
            "id": "482928449548294821",
            "primaryEmail": "amol@thoughtlabs.io",
            "emails_primary": "amol@altitudenetworks.com,mr.amolpatel@gmail.com,amol.canvas@gmail.com",
            "name_fullname": "Amol Patel",
            "name_givenname": "Amol",
            "name_familyname": "Patel",
        },
        {
            "id": "48284484594829",
            "primaryEmail": "yasuke@shogun.jp",
            "emails_primary": "daikokuten@yaske.shogun,pluto@sweatband.org,yasuke@tech.info",
            "name_fullname": "Daimyo Yasuke",
            "name_givenname": "Daimyo",
            "name_familyname": "Yasuke",
        },
    ]


@pytest.fixture
def admin_directory_v1_tokens_data():
    return [
        {
            "id_db": "1",
            "kind": "admin#directory#token",
            "etag": "'GPUJN6YVAOElesyqxtgGs7jrFWY/GTZ5tOjbpz8HdJ2V_AHOZ_K-X60'",
            "clientId": "261251194779.apps.googleusercontent.com",
            "displayText": "Google APIs Explorer",
            "anonymous": "0",
            "nativeApp": "0",
            "userKey": "106502887677037886472",
            "scope": "https://www.googleapis.com/auth/admin.directory.orgunit",
            "dt_created": "2018-06-07 03:28:58",
            "dt_modified": "2019-02-21 10:00:26",
            "has_marketplace_app": None,
            "marketplace_icon": None,
        },
    ]


@pytest.fixture
def admin_reports_v1_drive_data():
    return [
        {
            "id_uniqueQualifier": "1373419702667885644",
            "event_name": "download",
            "event_type": "access",
            "doc_id": "19SqoY_J69I-zSD78xWcEGnZGuMKwUY0p",
            "doc_title": "Private personal secret secure financial - edited again",
            "id_time": "2020-07-10T17:48:41",
            "originating_app_id": "261251194779",
            "actor_email": "bobbie@thoughtlabs.io",
            "target_user": None,
            "ipaddress": "50.233.123.210",
            "membership_change_type": None,
            "old_value": None,
            "new_value": None,
            "source_folder_title": None,
            "destination_folder_title": None,
            "old_visibility": None,
            "visibility": "private",
            "visibility_change": None,
        },
        {
            "id_uniqueQualifier": "154798243160324952",
            "event_name": "change_user_access",
            "event_type": "acl_change",
            "doc_id": "16mKl4YxXv2er1TO7VjPx0hfrv7LhcQKe",
            "doc_title": "Confidential Board Deck3.pdf",
            "actor_email": "michael@thoughtlabs.io",
            "target_user": "mwcoates@gmail.com",
            "ipaddress": "148.64.99.45",
            "membership_change_type": "",
            "old_value": "",
            "new_value": "can_edit",
            "source_folder_title": "",
            "destination_folder_title": "",
            "old_visibility": "private",
            "visibility": "shared_externally",
            "visibility_change": "external",
        },
        {
            "id_uniqueQualifier": "154798243160324954",
            "event_name": "change_user_access",
            "event_type": "acl_change",
            "doc_id": "16mKl4YxXv2er1TO7VjPx0hfrv7LhcQKe",
            "doc_title": "Confidential Board Deck3.pdf",
            "actor_email": None,
            "actor_profileId": "498492484439585393",
            "target_user": "nyahc@test.io",
            "ipaddress": "223.49.4859.284",
            "membership_change_type": "",
            "old_value": "",
            "new_value": "can_edit",
            "source_folder_title": "",
            "destination_folder_title": "",
            "old_visibility": "private",
            "visibility": "shared_externally",
            "visibility_change": "external",
        },
        {
            "id_uniqueQualifier": "484293844924847887",
            "event_name": "change_user_access",
            "event_type": "acl_change",
            "doc_id": "1ZQDwKMLCyKvRvImc6IdpWtxR7m9Drg0w",
            "doc_title": "Confidential Board Deck3.pdf",
            "actor_email": "michael@thoughtlabs.io",
            "target_user": "mwcoates@gmail.com",
            "ipaddress": "148.64.99.45",
            "membership_change_type": "",
            "old_value": "",
            "new_value": "can_edit",
            "source_folder_title": "",
            "destination_folder_title": "",
            "old_visibility": "private",
            "visibility": "shared_externally",
            "visibility_change": "external",
        },
        {
            "id_uniqueQualifier": "154798243160324953",
            "event_name": "change_user_access",
            "event_type": "acl_change",
            "doc_id": "1ZQDwKMLCyKvRvImc6IdpWtxReeiqeodl",
            "doc_title": "Confidential Board Deck4.pdf",
            "actor_email": "michael@thoughtlabs.io",
            "target_user": "mwcoates@gmail.com",
            "ipaddress": "534.24.48.33",
            "membership_change_type": "",
            "old_value": "",
            "new_value": "can_edit",
            "source_folder_title": "",
            "destination_folder_title": "",
            "old_visibility": "private",
            "visibility": "shared_externally",
            "visibility_change": "external",
        },
        {
            "id_uniqueQualifier": "448934539484829485",
            "event_name": "change_user_access",
            "event_type": "acl_change",
            "doc_id": "1ZQDwKMLCyKvRvImc6IdpWtxReeiqeodl",
            "doc_title": "Confidential Board Deck4.pdf",
            "actor_email": "",
            "target_user": "check.nyah@gmail.com",
            "ipaddress": "4284.23829.48924.32",
            "membership_change_type": "",
            "old_value": "",
            "new_value": "can_edit",
            "source_folder_title": "",
            "destination_folder_title": "",
            "old_visibility": "private",
            "visibility": "shared_externally",
            "visibility_change": "external",
        },
    ]


@pytest.fixture
def drive_v3_filesmeta_data():
    return [
        {
            "file_id": "1lCkT-e66TNCzFo6LEw696tqJj9ozzhP7qY2uy-5p1ZI",
            "file_name": "Private personal secret secure financial - edited again",
            "file_mimeType": "application/vnd.google-apps.document",
            "trashed": False,
            "md5Checksum": "d41d8cd98f00b204e9800998ecf8427e",
            "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.document",
            "createdTime": "2019-04-05T17:30:33",
            "modifiedTime": "2020-07-10T17:48:41",
            "owners_emailAddress": "michael@thoughtlabs.io",
            "permissions_id": "01418317513357223822",
            "permissions_type": "user",
            "permissions_emailAddress": "michael@thoughtlabs.io",
            "permissions_displayName": "Michael Coates",
            "permissions_role": "owner",
            "permissions_domain": None,
            "permissions_allowFileDiscovery": True,
            "permissions_status": None,
            "parents_list": "082948x3l48",
            "webViewLink": "web_view_link_1",
        },
        {
            "file_id": "1BuZUfN1vykrDjPi6zlEr8CtoIwiYQJ1n",
            "file_name": "dependency_links.txt",
            "file_mimeType": "application/vnd.google-apps.document",
            "trashed": False,
            "md5Checksum": "d41d8cd98f00b204e9800998ecf8427e",
            "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.document",
            "createdTime": "2019-04-05T17:30:33",
            "modifiedTime": "2020-11-16T17:48:41",
            "owners_emailAddress": "michael@thoughtlabs.io",
            "permissions_id": "01418314232403493553834",
            "permissions_type": "user",
            "permissions_emailAddress": "nyah@thoughtlabs.biz",
            "permissions_displayName": "Nyah Check",
            "permissions_role": "owner",
            "permissions_domain": None,
            "permissions_allowFileDiscovery": True,
            "permissions_status": "PENDING",
            "parents_list": "082948x3l48",
            "webViewLink": "web_view_link_2",
        },
        {
            "file_id": "195AwU1HlKBdOWTXzfF_irREGfqMDB1d4",
            "file_name": "requirements-specs.doc",
            "file_mimeType": "application/vnd.google-apps.document",
            "trashed": False,
            "md5Checksum": "d41d8cd98f00b204e9800998ecf8427e",
            "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.document",
            "createdTime": "2019-04-05T17:30:33",
            "modifiedTime": "2020-11-16T17:48:41",
            "owners_emailAddress": "michael@thoughtlabs.io",
            "permissions_id": "4239403049230923348024",
            "permissions_type": "user",
            "permissions_emailAddress": "check.nyah@gmail.com",
            "permissions_displayName": "Nyah Check",
            "permissions_role": "owner",
            "permissions_domain": None,
            "permissions_allowFileDiscovery": True,
            "parents_list": "082948x3l48",
            "permissions_status": "REMOVED",
            "webViewLink": "web_view_link_3",
        },
        {
            "file_id": "4823984lr2li3eli2eli",
            "file_name": "DC Metro plan.docx",
            "file_mimeType": "application/vnd.google-apps.document",
            "trashed": False,
            "md5Checksum": "d41d8cd98f00b204e9800998ecf8427e",
            "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.document",
            "createdTime": "2019-04-05T17:30:33",
            "modifiedTime": "2020-11-16T17:48:41",
            "owners_emailAddress": "nyah@thoughtlabs.io",
            "permissions_id": "42802038238534944829",
            "permissions_type": "user",
            "permissions_emailAddress": "nyahc@tech.biz",
            "permissions_displayName": "Nyah Check",
            "permissions_role": "owner",
            "permissions_domain": None,
            "permissions_allowFileDiscovery": True,
            "parents_list": "082948x3l48",
            "permissions_status": "REMOVED",
            "webViewLink": "web_view_link_4",
        },
        {
            "file_id": "482398SSEE3LDL3.WE",
            "file_name": "San Francisco Chronicle meeting.txt",
            "file_mimeType": "application/vnd.google-apps.document",
            "trashed": False,
            "md5Checksum": "d41d8cd98f00b204e9800998ecf8427e",
            "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.document",
            "createdTime": "2019-04-05T17:30:33",
            "modifiedTime": "2020-11-16T17:48:41",
            "owners_emailAddress": "nyah@thoughtlabs.io",
            "permissions_id": "5593485281327382",
            "permissions_type": "user",
            "permissions_emailAddress": "nyah-at-nasak@space.x",
            "permissions_displayName": "Nyah Check",
            "permissions_role": "owner",
            "permissions_domain": None,
            "permissions_allowFileDiscovery": True,
            "parents_list": "082948x3l48",
            "permissions_status": "PENDING",
            "webViewLink": "web_view_link_5",
        },
        {
            "file_id": "082948x3l48",
            "file_name": "fake-documents-folder",
            "file_mimeType": "application/vnd.google-apps.folder",
            "trashed": False,
            "md5Checksum": "d41d8cd98f00b204e9800998ecf8427e",
            "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.folder",
            "createdTime": "2019-04-05T17:30:33",
            "modifiedTime": "2020-07-10T17:48:41",
            "owners_emailAddress": "bobbie@thoughtlabs.io",
            "permissions_id": "01418317513357223822",
            "permissions_type": "user",
            "permissions_emailAddress": "bobbie@thoughtlabs.io",
            "permissions_displayName": "Bobbie Hawaii",
            "permissions_role": "owner",
            "permissions_domain": None,
            "permissions_allowFileDiscovery": True,
            "parents_list": "fake-root-folder",
            "webViewLink": "web_view_link_6",
        },
        {
            "file_id": "13LIVQvVpynppp-JscuLdDAc5xplpWQTE",
            "file_name": "merit pablo personal email test folder",
            "file_mimeType": "application/vnd.google-apps.folder",
            "trashed": False,
            "md5Checksum": "44dld8233l",
            "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.folder",
            "createdTime": "2021-02-05T18:30:30",
            "modifiedTime": "2020-02-10T19:48:38",
            "owners_emailAddress": "bobbie@thoughtlabs.io",
            "permissions_id": "01418317513357223822",
            "permissions_type": "user",
            "permissions_emailAddress": "bobbie@thoughtlabs.io",
            "permissions_displayName": "Bobbie Hawaii",
            "permissions_role": "owner",
            "permissions_domain": None,
            "permissions_allowFileDiscovery": True,
            "parents_list": "0AGnKU4VH9-QzUk9PVA",
            "webViewLink": "web_view_link_7",
        },
    ]


@pytest.fixture
def email_identification_data():
    return [
        {
            "company_emailAddress": "nyah@thoughtlabs.io",
            "confidence": 100,
            "false_positive": 0,
            "id_db": 11,
            "permissions_last_deleted_on_datetime": datetime_tools.format_iso_datetime_for_mysql(
                datetime_tools.get_curr_utc_time()
            ),
            "personal_emailAddress": "nyah-at-nasak@space.x",
            "status": "PENDING",
            "platform_id": "1",
        },
        {
            "company_emailAddress": "nyah@thoughtlabs.io",
            "confidence": 100,
            "false_positive": 0,
            "id_db": 12,
            "permissions_last_deleted_on_datetime": datetime_tools.format_iso_datetime_for_mysql(
                datetime_tools.get_curr_utc_time()
            ),
            "personal_emailAddress": "nyahc@test.biz",
            "status": "REMOVED",
            "platform_id": "1",
        },
        {
            "company_emailAddress": "nyah@thoughtlabs.io",
            "confidence": 100,
            "false_positive": 0,
            "id_db": 13,
            "permissions_last_deleted_on_datetime": datetime_tools.format_iso_datetime_for_mysql(
                datetime_tools.get_curr_utc_time()
            ),
            "personal_emailAddress": "check.nyah@gmail.com",
            "status": "REMOVED",
            "platform_id": "1",
        },
        {
            "company_emailAddress": "nyah@thoughtlabs.io",
            "confidence": 100,
            "false_positive": 0,
            "id_db": 14,
            "permissions_last_deleted_on_datetime": datetime_tools.format_iso_datetime_for_mysql(
                datetime_tools.get_curr_utc_time()
            ),
            "personal_emailAddress": "nyah@thoughtlabs.biz",
            "status": "REMOVED",
            "platform_id": "1",
        },
        {
            "company_emailAddress": "michael@thoughtlabs.io",
            "confidence": 100,
            "false_positive": 1,
            "id_db": 22,
            "permissions_last_deleted_on_datetime": None,
            "personal_emailAddress": "mwcoates@gmail.com",
            "status": "ACTIVE",
            "platform_id": "1",
        },
        {
            "company_emailAddress": "yasuke@shogun.jp",
            "confidence": 100,
            "false_positive": 0,
            "id_db": 44,
            "permissions_last_deleted_on_datetime": datetime_tools.format_iso_datetime_for_mysql(
                datetime_tools.get_curr_utc_time()
            ),
            "personal_emailAddress": "daikokuten@yaske.shogun",
            "status": "ACTIVE",
            "platform_id": "1",
        },
    ]


@pytest.fixture
def files_content_inspection_data():
    return [
        {
            "platform_id": "1",
            "file_id": "1lCkT-e66TNCzFo6LEw696tqJj9ozzhP7qY2uy-5p1ZI",
            "content_inspected_last_dt": "2020-07-10T17:48:41",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "content_tin_count": None,
            "content_ccn_count": "3",
            "content_sensitive_kw_counts": json_tools.dumps(
                [
                    {"count": 1, "keyword": "Attorney"},
                    {"count": 9, "keyword": "Attorney/Client"},
                    {"count": 6, "keyword": "board meeting"},
                    {"count": 2, "keyword": "proprietary"},
                    {"count": 0, "keyword": "invalid-key"},
                ]
            ),
        },
        {
            "platform_id": "1",
            "file_id": "1BuZUfN1vykrDjPi6zlEr8CtoIwiYQJ1n",
            "content_inspected_last_dt": "2020-07-10T17:40:41",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "content_tin_count": None,
            "content_ccn_count": "1",
            "content_sensitive_kw_counts": json_tools.dumps(
                [
                    {"count": 1, "keyword": "Attorney"},
                    {"count": 2, "keyword": "Attorney/Client"},
                    {"count": 4, "keyword": "board meeting"},
                    {"count": 2, "keyword": "proprietary"},
                    {"count": 4, "keyword": "invalid-key"},
                ]
            ),
        },
        {
            "platform_id": "1",
            "file_id": "195AwU1HlKBdOWTXzfF_irREGfqMDB1d4",
            "content_inspected_last_dt": "2020-07-10T17:48:46",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "content_tin_count": None,
            "content_ccn_count": None,
            "content_sensitive_kw_counts": json_tools.dumps(
                [
                    {"count": 1, "keyword": "Attorney"},
                    {"count": 1, "keyword": "Attorney/Client"},
                    {"count": 5, "keyword": "board meeting"},
                    {"count": 5, "keyword": "proprietary"},
                    {"count": 8, "keyword": "invalid-key"},
                ]
            ),
        },
        {
            "platform_id": "1",
            "file_id": "4823984lr2li3eli2eli",
            "content_inspected_last_dt": "2020-07-10T17:48:46",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "content_tin_count": 1,
            "content_ccn_count": 1,
            "content_sensitive_kw_counts": "[]",
        },
        {
            "platform_id": "1",
            "file_id": "482398SSEE3LDL3.WE",
            "content_inspected_last_dt": "2020-07-10T17:48:46",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "content_tin_count": None,
            "content_ccn_count": 2,
            "content_sensitive_kw_counts": "",
        },
        {
            "file_id": "1s2ayrDcrl3-7UBJp1T380hYANl3ZDcMx",
            "content_inspected_last_dt": "2020-07-10T17:48:41",
            "dt_created": "2020-09-09T17:30:33",
            "dt_modified": "2020-11-02T17:48:41",
            "content_tin_count": None,
            "content_ccn_count": "4",
            "content_sensitive_kw_counts": json_tools.dumps(
                [
                    {"count": 9, "keyword": "Amba"},
                    {"count": 6, "keyword": "boyses"},
                    {"count": 2, "keyword": "proprietary"},
                    {"count": 1, "keyword": "Attorney"},
                    {"count": 0, "keyword": "invalid-key"},
                ]
            ),
        },
    ]


@pytest.fixture
def platform_data():
    return [
        {
            "id": 1,
            "symbolic_name": "gsuite",
            "name": "Google Workspace",
        },
        {
            "id": 2,
            "symbolic_name": "o365",
            "name": "Microsoft Office 365",
        },
    ]


@pytest.fixture
def risks_files_data():
    return [
        {
            "risk_type_id": "3010",
            "risk_id": "0fbc1911c7085749fd38b4d327698f3f5fa5d228",
            "file_id": "1lCkT-e66TNCzFo6LEw696tqJj9ozzhP7qY2uy-5p1ZI",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "permissions_id": "01418317513357223822",
            "owners_emailAddress": "michael@thoughtlabs.io",
            "permissions_emailAddress": "michael@thoughtlabs.io",
            "platform_id": 1,
        },
        {
            "risk_type_id": "1020",
            "risk_id": "33433cb47e6dc7097b1622d564c80a85ae8c9a30",
            "file_id": "1BuZUfN1vykrDjPi6zlEr8CtoIwiYQJ1n",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "permissions_id": "01418314232403493553834",
            "owners_emailAddress": "michael@thoughtlabs.io",
            "permissions_emailAddress": "nyah@thoughtlabs.biz",
            "platform_id": 1,
        },
        {
            "risk_type_id": "1020",
            "risk_id": "33433cb47e6dc7097b1622d564c80a85ae8c9a30",
            "file_id": "195AwU1HlKBdOWTXzfF_irREGfqMDB1d4",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "permissions_id": "4239403049230923348024",
            "owners_emailAddress": "michael@thoughtlabs.io",
            "permissions_emailAddress": "check.nyah@gmail.com",
            "platform_id": 1,
        },
        {
            "risk_type_id": "3100",
            "risk_id": "gtereflig4392398ge2l3i323984293",
            "file_id": "4823984lr2li3eli2eli",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "permissions_id": "42802038238534944829",
            "owners_emailAddress": "nyah@thoughtlabs.io",
            "permissions_emailAddress": "nyahc@tech.biz",
            "platform_id": 1,
        },
        {
            "risk_type_id": "3100",
            "risk_id": "gtereflig4392398ge2l3i323984293",
            "file_id": "482398SSEE3LDL3.WE",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "permissions_id": "5593485281327382",
            "owners_emailAddress": "nyah@thoughtlabs.io",
            "permissions_emailAddress": "nyah-at-nasak@space.x",
            "platform_id": 1,
        },
        {
            "file_id": "4823984lr2li3eli2eli",
            "risk_id": "c8e6abdce150347e0be92285376be530f8c01233",
            "risk_type_id": 3100,
            "permissions_id": "5593485281327382",
            "dt_created": "2020-10-14 00:00:00",
            "dt_modified": "2020-10-14 23:17:50",
            "platform_id": 1,
        },
        {
            "file_id": "482398SSEE3LDL3.WE",
            "risk_id": "3b6e9676ffc24b04bebbd1eecd7f42d2",
            "risk_type_id": 3100,
            "permissions_id": "5593485281327382",
            "dt_created": "2020-10-14 00:00:00",
            "dt_modified": "2020-10-14 20:46:39",
            "platform_id": 1,
        },
        {
            "risk_type_id": "1020",
            "risk_id": "8lr2ieel8492leediadelelewl32dksle",
            "file_id": "015XDZUDG42SYYNSTFNNBZNZYK4QAGDBJA",
            "dt_created": "2021-04-29T17:30:33",
            "dt_modified": "2021-05-20T17:48:41",
            "permissions_id": "4820384844928449238492",
            "owners_emailAddress": "pulkit@thoughtlabs00.onmicrosoft.com",
            "permissions_emailAddress": "nyah@thoughtlabs.io",
            "platform_id": 2,
        },
        {
            "risk_type_id": "1020",
            "risk_id": "8lr2ieel8492leediadelelewl32dksle",
            "file_id": "015XDZUDBNXD3NQIBXRFGLUHMWKBV3NUJP",
            "dt_created": "2021-04-29T17:30:33",
            "dt_modified": "2021-05-20T17:48:41",
            "permissions_id": "94845348249454892",
            "owners_emailAddress": "pulkit@thoughtlabs00.onmicrosoft.com",
            "permissions_emailAddress": "check.nyah@gmail.com",
            "platform_id": 2,
        },
        {
            "risk_type_id": "3010",
            "risk_id": "fiel2i2e00102309cb129cd409df972752ce556",
            "file_id": "01LLW7TSH5Q6C7SGGYANHIBZJQJ5YK25H2",
            "dt_created": "2021-04-29T17:30:33",
            "dt_modified": "2021-05-20T17:48:41",
            "permissions_id": "4820384844928449238492",
            "owners_emailAddress": "bobbie@thoughtlabs00.onmicrosoft.com",
            "permissions_emailAddress": "nyah@thoughtlabs.io",
            "platform_id": 2,
        },
        {
            "risk_type_id": "3010",
            "risk_id": "fiel2i2e00102309cb129cd409df972752ce556",
            "file_id": "016MCEIVFUWWODSSBS4VFIULB3J5EUDEIH",
            "dt_created": "2021-04-29T17:30:33",
            "dt_modified": "2021-05-20T17:48:41",
            "permissions_id": "94845348249454892",
            "owners_emailAddress": "bobbie@thoughtlabs00.onmicrosoft.com",
            "permissions_emailAddress": "check.nyah@gmail.com",
            "platform_id": 2,
        },
        {
            "risk_type_id": "1050",
            "risk_id": "0fbc1911c7085749fd38b4d327698f3f5fa5d228",
            "file_id": "1s2ayrDcrl3-7UBJp1T380hYANl3ZDcMx",
            "dt_created": "2019-04-05T17:30:33",
            "dt_modified": "2020-07-10T17:48:41",
            "permissions_id": "0141831751335722482382",
            "owners_emailAddress": "bobbie@thoughtlabsio",
            "permissions_emailAddress": "pulkit@thoughtlabs.io",
            "platform_id": 1,
        },
        {
            "risk_type_id": "3100",
            "risk_id": "gtereflig4392398ge2l3i323984293",
            "file_id": "016MCEIVFUWWODSSBS4VFIU",
            "dt_created": "2021-05-29T17:30:33",
            "dt_modified": "2021-06-20T17:48:41",
            "permissions_id": "94845348249454892",
            "owners_emailAddress": "bobbie@thoughtlabs00.onmicrosoft.com",
            "permissions_emailAddress": "check.nyah@gmail.com",
            "platform_id": 2,
        },
        {
            "risk_type_id": "3100",
            "risk_id": "gtereflig4392398ge2l3i323984293",
            "file_id": "016MCEIVFUWWODSSBS4VFIUV",
            "dt_created": "2021-04-05T17:30:33",
            "dt_modified": "2021-06-10T17:48:41",
            "permissions_id": "42802038238534944829",
            "owners_emailAddress": "bobbie@thoughtlabs00.onmicrosoft.com",
            "permissions_emailAddress": "nyahc@tech.biz",
            "platform_id": 2,
        },
    ]


@pytest.fixture
def risk_reports_data():
    return [
        {
            "risk_id": "28c6d4819547a93fd68e2984ec4f7f9b47cd62ac",
            "risk_type_id": 3100,
            "original_risk_dt_created": "2020-10-14 00:00:00",
            "severity": 5,
            "risk_description": "Most Shared Files (Non-Company Owned)",
            "dt_created": "2021-04-13 00:00:00",
            "dt_modified": "2021-04-13 21:01:44",
        },
        {
            "risk_id": "c8e6abdce150347e0be92285376be530f8c01233",
            "risk_type_id": 3100,
            "original_risk_dt_created": "2020-10-14 00:00:00",
            "severity": 6,
            "risk_description": "Many files downloaded in 24 hours by employee",
            "dt_created": "2021-04-13 00:00:00",
            "dt_modified": "2021-04-13 23:17:50",
        },
        {
            "risk_id": "3b6e9676ffc24b04bebbd1eecd7f42d2",
            "risk_type_id": 3100,
            "original_risk_dt_created": "2020-10-14 00:00:00",
            "severity": 5,
            "risk_description": "Most Shared Files (Non-Company Owned)",
            "dt_created": "2021-04-13 00:00:00",
            "dt_modified": "2021-04-13 20:46:39",
        },
    ]


@pytest.fixture
def top_risks_data():
    return [
        {
            "id_db": "1214",
            "risk_id": "0fbc1911c7085749fd38b4d327698f3f5fa5d228",
            "risk_type_id": "3010",
            "risk_incident_date": None,
            "risk_target": "261251194779",
            "severity": "8",
            "file_id": "1lCkT-e66TNCzFo6LEw696tqJj9ozzhP7qY2uy-5p1ZI",
            "status": "active",
            "risk_person_id": "michael@thoughtlabs.io",
            "risk_description": "File Shared by Link - Externally Accessible",
            "permissions_id": None,
            "permissions_emailaddress": None,
            "file_owner_firstname": None,
            "file_owner_familyname": None,
            "file_owner_emailaddress": "michael@thoughtlabs.io",
            "file_collaborators": None,
            "file_collaborator_count": "0",
            "file_name": "Private personal secret secure financial - edited again",
            "file_count": "1",
            "owners_displayname": "Michael Coates",
            "owners_emailaddress": "michael@thoughtlabs.io",
            "owners_id": None,
            "application_displayText": None,
            "platform_id": "1",
        },
        {
            "id_db": "1215",
            "risk_id": "33433cb47e6dc7097b1622d564c80a85ae8c9a30",
            "risk_type_id": "1020",
            "risk_incident_date": None,
            "risk_target": None,
            "severity": "8",
            "file_id": None,
            "status": "active",
            "risk_target": None,
            "risk_person_id": "michael@thoughtlabs.io",
            "risk_description": "Company Owned File Shared by Link - Externally Accessible",
            "permissions_id": None,
            "permissions_emailaddress": None,
            "file_owner_firstname": None,
            "file_owner_familyname": None,
            "file_owner_emailaddress": None,
            "file_collaborators": None,
            "file_collaborator_count": "0",
            "file_name": None,
            "file_count": "2",
            "owners_displayname": "Michael Coates",
            "owners_emailaddress": "michael@thoughtlabs.io",
            "owners_id": None,
            "application_displayText": None,
            "platform_id": "1",
        },
        {
            "id_db": "1216",
            "risk_id": "gtereflig4392398ge2l3i323984293",
            "risk_type_id": "3100",
            "risk_incident_date": None,
            "risk_target": None,
            "severity": "7",
            "file_id": None,
            "status": "active",
            "risk_person_id": "nyah@thoughtlabs.io",
            "risk_description": "Weird File types",
            "permissions_id": None,
            "permissions_emailaddress": None,
            "file_owner_firstname": None,
            "file_owner_familyname": None,
            "file_owner_emailaddress": None,
            "file_collaborators": None,
            "file_collaborator_count": "0",
            "file_name": None,
            "file_count": "2",
            "owners_displayname": "Nyah Check",
            "owners_emailaddress": "nyah@thoughtlabs.io",
            "owners_id": None,
            "application_displayText": None,
            "platform_id": "1",
        },
        {
            "id_db": "1218",
            "risk_id": "8lr2ieel8492leediadelelewl32dksle",
            "risk_type_id": "1020",
            "risk_incident_date": None,
            "risk_target": None,
            "severity": "6",
            "app": "Office 365",
            "file_id": "",
            "status": "active",
            "risk_person_id": "nyah@thoughtlabs.io",
            "risk_description": "Company Owned File Shared by Link - Externally Accessible",
            "permissions_id": None,
            "permissions_emailaddress": None,
            "file_owner_firstname": None,
            "file_owner_familyname": None,
            "file_owner_emailaddress": None,
            "file_collaborators": None,
            "file_collaborator_count": "0",
            "file_name": None,
            "file_count": "2",
            "owners_displayname": "Pulkit Khetrapal",
            "owners_emailaddress": "pulkit@thoughtlabs00.onmicrosoft.com",
            "owners_id": None,
            "application_displayText": None,
            "platform_id": "2",
        },
        {
            "id_db": "1220",
            "risk_id": "fiel2i2e00102309cb129cd409df972752ce556",
            "risk_type_id": "3010",
            "risk_incident_date": None,
            "risk_target": "0f9e59ce-494b-4e0c-95d2-5931562a7b86",
            "severity": "5",
            "app": "Office 365",
            "file_id": None,
            "status": "active",
            "risk_person_id": "nyah@thoughtlabs.io",
            "risk_description": "Many company owned files downloaded in 24 hours by app on behalf of a user",
            "permissions_id": None,
            "permissions_emailaddress": None,
            "file_owner_firstname": None,
            "file_owner_familyname": None,
            "file_owner_emailaddress": None,
            "file_collaborators": None,
            "file_collaborator_count": "0",
            "file_name": None,
            "file_count": "2",
            "owners_displayname": "Pulkit Khetrapal",
            "owners_emailaddress": "amir@thoughtlabs00.onmicrosoft.com",
            "owners_id": None,
            "application_displayText": None,
            "platform_id": "2",
        },
    ]


################################
## MS OFFICE TABLE FIXTURE DATA
################################
@pytest.fixture
def ms_applications_data():
    return [
        {
            "id_db": 1,
            "dt_created": "2021-04-13T20:58:54",
            "dt_modified": "2021-04-13T20:58:54",
            "ms_id": "0c10dda7-8420-46d9-bfa3-5551bbcf134e",
            "ms_dt_created": "2021-01-13T20:29:44",
            "ms_dt_deleted": None,
            "app_id": "0f9e59ce-494b-4e0c-95d2-5931562a7b86",
            "app_template_id": None,
            "display_name": "Thought Labs MS Office Integration",
            "description": None,
            "group_membership_claims": None,
            "identifier_uris": None,
            "is_device_only_auth_supported": None,
            "is_fallback_public_client": None,
            "notes": None,
            "optional_claims": None,
            "publisher_domain": "thoughtlabs00.onmicrosoft.com",
            "sign_in_audience": "AzureADMyOrg",
            "parental_control_legal_age_group_rule": "Allow",
            "parental_control_countries_blocked_for_minors": None,
        },
        {
            "id_db": 2,
            "dt_created": "2021-04-13T20:58:54",
            "dt_modified": "2021-04-13T20:58:54",
            "ms_id": "cabc463b-2d3d-4fea-8c59-098fa67e3c26",
            "ms_dt_created": "2021-04-05T18:07:48",
            "ms_dt_deleted": None,
            "app_id": "300a8067-6d41-4656-8b43-8a38d900990a",
            "app_template_id": None,
            "display_name": "Thought Labs Teams App",
            "description": None,
            "group_membership_claims": None,
            "identifier_uris": None,
            "is_device_only_auth_supported": None,
            "is_fallback_public_client": None,
            "notes": None,
            "optional_claims": None,
            "publisher_domain": "thoughtlabs00.onmicrosoft.com",
            "sign_in_audience": "AzureADMultipleOrgs",
            "parental_control_legal_age_group_rule": "Allow",
            "parental_control_countries_blocked_for_minors": None,
        },
        {
            "id_db": 3,
            "dt_created": "2021-04-13T20:58:54",
            "dt_modified": "2021-04-13T20:58:54",
            "ms_id": "faf658ab-8904-40d6-afd5-855ac25c5dab",
            "ms_dt_created": "2020-10-30T17:58:05",
            "ms_dt_deleted": None,
            "app_id": "e03ef25d-e14d-434a-a609-8f8874d191cb",
            "app_template_id": None,
            "display_name": "DevTest ms_scraper test",
            "description": None,
            "group_membership_claims": None,
            "identifier_uris": None,
            "is_device_only_auth_supported": None,
            "is_fallback_public_client": None,
            "notes": None,
            "optional_claims": None,
            "publisher_domain": "thoughtlabs00.onmicrosoft.com",
            "sign_in_audience": "AzureADandPersonalMicrosoftAccount",
            "api_requested_access_token_version": 2,
            "parental_control_legal_age_group_rule": "Allow",
            "parental_control_countries_blocked_for_minors": None,
        },
    ]


@pytest.fixture
def ms_audit_sharepoint_data():
    return [
        {
            "id_db": "1",
            "ms_id": "1",
            "ms_dt_created": "2021-06-10T17:48:41",
            "operation": "FileDownloaded",
            "record_type": "SharePoint",
            "organization_id": "new-org",
            "user_id": "bobbie@thoughtlabs.io",
            "ms_doc_id": "fake-doc-id",
            "ms_drive_id": "fake-drive-id",
            "client_ip": "fake-ip-address",
            "app_id": "unknown-app-id",
            "object_drive_web_url": "drive_web_url_1",
            "object_path": "object_path_1",
        },
        {
            "id_db": "2",
            "ms_id": "2",
            "ms_dt_created": "2021-06-10T17:48:41",
            "operation": "FileDownloaded",
            "record_type": "SharePoint",
            "organization_id": "new-org",
            "user_id": "bobbie@thoughtlabs.io",
            "ms_doc_id": "fake-doc-id-2",
            "ms_drive_id": "fake-drive-id",
            "client_ip": "fake-ip-address",
            "app_id": None,
            "object_drive_web_url": "drive_web_url_1",
            "object_path": "object_path_1",
        },
        {
            "id_db": "3",
            "ms_id": "3",
            "ms_dt_created": "2021-06-10T17:48:41",
            "operation": "AddedToSecureLink",
            "record_type": "SharePointSharingOperation",
            "organization_id": "new-org",
            "user_id": "bobbie@thoughtlabs.io",
            "ms_doc_id": "fake-doc-id-3",
            "ms_drive_id": "fake-drive-id",
            "client_ip": "fake-ip-address",
            "app_id": None,
            "object_drive_web_url": "drive_web_url_1",
            "object_path": "object_path_1",
        },
        {
            "id_db": "4",
            "ms_id": "4",
            "ms_dt_created": "2021-06-10T17:48:41",
            "operation": "CompanyLinkCreated",
            "record_type": "SharePointSharingOperation",
            "organization_id": "new-org",
            "user_id": "nyah@thoughtlabs.io",
            "target_name": "bobbie@thoughtlabs.io",
            "ms_doc_id": "fake-doc-id-4",
            "ms_drive_id": "fake-drive-id",
            "client_ip": "fake-ip-address",
            "app_id": None,
            "object_path": "object_path_1",
            "object_drive_web_url": "drive_web_url_1",
        },
        {
            "id_db": "5",
            "ms_id": "5",
            "ms_dt_created": "2021-06-10T17:58:51",
            "operation": "SharingSet",
            "record_type": "SharePointSharingOperation",
            "organization_id": "new-org",
            "user_id": "bobbie@thoughtlabs.io",
            "target_name": "check.nyah@gmail.com",
            "ms_doc_id": "fake-doc-id-5",
            "ms_drive_id": "fake-drive-id",
            "client_ip": "fake-ip-address",
            "app_id": None,
            "object_path": "object_path_1",
            "object_drive_web_url": "drive_web_url_1",
        },
    ]


@pytest.fixture
def ms_audit_azure_ad_data():
    return []


@pytest.fixture
def ms_drives_docs_data():
    return [
        {
            "id_db": 1,
            "dt_created": "2020-12-02T23:01:15",
            "dt_modified": "2021-05-19T00:55:22",
            "ms_id": "015XDZUDG42SYYNSTFNNBZNZYK4QAGDBJA",
            "ms_drive_id": "fake-drive-id",
            "ms_dt_created": "2020-10-30T19:39:41",
            "ms_dt_modified": "2020-10-30T19:39:41",
            "name": "Book.xlsx",
            "download_url": "https://thoughtlabs00-my.sharepoint.com/personal/pulkit_thoughtlabs00_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=86b1d4dc-65ca-436b-96e7-0ae400618520&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdGhvdWdodGxhYnMwMC1teS5zaGFyZXBvaW50LmNvbUAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjIxMzg1NzE2IiwiZXhwIjoiMTYyMTM4OTMxNiIsImVuZHBvaW50dXJsIjoiS0QydzU5SFduS2ZjWVV1c3ZJalprSWpubGRVbTVRRmQ5NThTaHFpREpRTT0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE3MyIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiWm1ReVptVmxPRFF0WmpRek1pMDBabU0zTFdJek56TXRZVGRoWldFME9XSXhOams0IiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ik5qQmlPVFUwTnpjdE1UZ3haaTAwTmpsbUxUZ3dPRFF0TW1RM04yVXpZbUZsT1dKaSIsImFwcF9kaXNwbGF5bmFtZSI6IkFsdGl0dWRlIG1zX3NjcmFwZXIgdGVzdCIsIm5hbWVpZCI6ImUwM2VmMjVkLWUxNGQtNDM0YS1hNjA5LThmODg3NGQxOTFjYkAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJyb2xlcyI6Imdyb3VwLnJlYWQgYWxsc2l0ZXMucmVhZCBhbGxmaWxlcy5yZWFkIGFsbHNpdGVzLmZ1bGxjb250cm9sIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjEiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.NG5pRkhYYVB1eEhlajZNZTFLcDRDMHpya3BaSm91MkM4WEZtV0VvMnZGdz0&ApiVersion=2.0",
            "web_url": "https://thoughtlabs00-my.sharepoint.com/personal/pulkit_thoughtlabs00_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B86B1D4DC-65CA-436B-96E7-0AE400618520%7D&file=Book.xlsx&action=default&mobileredirect=true",
            "e_tag": None,
            "c_tag": '1""',
            "size": None,
            "created_by_type": '1""',
            "created_by_display_name": 0,
            "created_by_email": "pulkit@thoughtlabs00.onmicrosoft.com",
            "created_by_id": "Pulkit Khetrapal",
            "modified_by_display_name": "79c2e5fd-cab9-4a42-a045-ba8d7b1fc612",
            "modified_by_email": "user",
            "modified_by_id": "Pulkit Khetrapal",
            "file_mime_type": "document",
            "file_xor_hash": "79c2e5fd-cab9-4a42-a045-ba8d7b1fc612",
            "remote_tenant_id": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "remote_site_id": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=",
            "remote_drive_id": None,
            "is_internal": None,
            "created_by_domain": "thoughtlabs00.onmicrosoft.com",
            "parent_id": "01D3GIE3GV6Y2GOVW442325BZO354PWSELRRZ",
            "parent_path": "/drives/b!pKnEGmj9w0SAWDEqpTYU0JtY8iv1nQhOiF7cqt_iY-MVqLscgbIjRbBgGH7B3l62/root:/top-level-folder",
            "ms_path": "object_path_1",
        },
        {
            "id_db": 2,
            "dt_created": "2020-12-02T23:01:15",
            "dt_modified": "2021-05-19T00:55:22",
            "ms_id": "015XDZUDBNXD3NQIBXRFGLUHMWKBV3NUJP",
            "ms_drive_id": "fake-drive-id",
            "ms_dt_created": "2020-10-30T19:38:39",
            "ms_dt_modified": "2020-10-30T19:38:41",
            "name": "Document.docx",
            "download_url": "https://thoughtlabs00-my.sharepoint.com/personal/pulkit_thoughtlabs00_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=d8f6b82d-3720-4c89-ba1d-96506bb6d12f&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdGhvdWdodGxhYnMwMC1teS5zaGFyZXBvaW50LmNvbUAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjIxMzg1NzE2IiwiZXhwIjoiMTYyMTM4OTMxNiIsImVuZHBvaW50dXJsIjoiYlk0cHduUGYxMm9DVTYySnByRGxkMGNiNng2bnc1YjRpTURJZ1d6Rk5kbz0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE3MyIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiWm1ReVptVmxPRFF0WmpRek1pMDBabU0zTFdJek56TXRZVGRoWldFME9XSXhOams0IiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ik5qQmlPVFUwTnpjdE1UZ3haaTAwTmpsbUxUZ3dPRFF0TW1RM04yVXpZbUZsT1dKaSIsImFwcF9kaXNwbGF5bmFtZSI6IkFsdGl0dWRlIG1zX3NjcmFwZXIgdGVzdCIsIm5hbWVpZCI6ImUwM2VmMjVkLWUxNGQtNDM0YS1hNjA5LThmODg3NGQxOTFjYkAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJyb2xlcyI6Imdyb3VwLnJlYWQgYWxsc2l0ZXMucmVhZCBhbGxmaWxlcy5yZWFkIGFsbHNpdGVzLmZ1bGxjb250cm9sIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjEiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.NHhleDJ3VytrM1dGR3N0a3F5YWlOOVBuaHNSc25jRnI1SkdVb0hES1prQT0&ApiVersion=2.0",
            "web_url": "https://thoughtlabs00-my.sharepoint.com/personal/pulkit_thoughtlabs00_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BD8F6B82D-3720-4C89-BA1D-96506BB6D12F%7D&file=Document.docx&action=default&mobileredirect=true",
            "e_tag": None,
            "c_tag": '2""',
            "size": None,
            "created_by_type": '2""',
            "created_by_display_name": 11019,
            "created_by_email": "pulkit@thoughtlabs00.onmicrosoft.com",
            "created_by_id": "Pulkit Khetrapal",
            "modified_by_display_name": "79c2e5fd-cab9-4a42-a045-ba8d7b1fc612",
            "modified_by_email": "user",
            "modified_by_id": "Pulkit Khetrapal",
            "file_mime_type": "document",
            "file_xor_hash": "79c2e5fd-cab9-4a42-a045-ba8d7b1fc612",
            "remote_tenant_id": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "remote_site_id": "yGa64ojJGaq/L05/Q2oVxgPRbjc=",
            "remote_drive_id": None,
            "ms_path": "object_path_1",
            "is_internal": None,
            "created_by_domain": "thoughtlabs00.onmicrosoft.com",
            "parent_id": "01D3GIE3GV6Y2GOVW442325BZO354PWSELRRZ",
            "parent_path": "/drives/b!pKnEGmj9w0SAWDEqpTYU0JtY8iv1nQhOiF7cqt_iY-MVqLscgbIjRbBgGH7B3l62/root:/top-level-folder",
        },
        {
            "id_db": 3,
            "dt_created": "2020-12-02T23:01:15",
            "dt_modified": "2021-05-19T00:55:21",
            "ms_id": "01LLW7TSH5Q6C7SGGYANHIBZJQJ5YK25H2",
            "ms_drive_id": "fake-drive-id",
            "ms_dt_created": "2020-10-30T19:16:17",
            "ms_dt_modified": "2020-10-30T19:16:37",
            "name": "a new document under Bobbie Test Shared Site.docx",
            "download_url": "https://thoughtlabs00.sharepoint.com/sites/BobbieTestSite/_layouts/15/download.aspx?UniqueId=f98587fd-d818-4e03-80e5-304f70ad74fa&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdGhvdWdodGxhYnMwMC5zaGFyZXBvaW50LmNvbUAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjIxMzg1NzE3IiwiZXhwIjoiMTYyMTM4OTMxNyIsImVuZHBvaW50dXJsIjoiWlBib3loc2ZFbVMxNU1KU1lXeExFdE1CZ1I0cERuMXFndHVqRHAwTlcrdz0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE0MyIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiTVRjNE5UTmpZVGd0WW1VMFlTMDBNVEppTFRnNU1qUXRNR1V6TkdJek5UQXdORFJqIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6IlpEa3lPR0k0T1RJdFkyTTROQzAwTVdRMExUZzVaRFV0T1dOallUTTBORFUzWWpRNSIsImFwcF9kaXNwbGF5bmFtZSI6IkFsdGl0dWRlIG1zX3NjcmFwZXIgdGVzdCIsIm5hbWVpZCI6ImUwM2VmMjVkLWUxNGQtNDM0YS1hNjA5LThmODg3NGQxOTFjYkAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJyb2xlcyI6Imdyb3VwLnJlYWQgYWxsc2l0ZXMucmVhZCBhbGxmaWxlcy5yZWFkIGFsbHNpdGVzLmZ1bGxjb250cm9sIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjEiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.UEE4eEVvYTVzWjdxd3VOYktKaXV5MUN1OVlPUUdFSEJvWXBJQ0ZFT1pPaz0&ApiVersion=2.0",
            "web_url": "https://thoughtlabs00.sharepoint.com/sites/BobbieTestSite/_layouts/15/Doc.aspx?sourcedoc=%7BF98587FD-D818-4E03-80E5-304F70AD74FA%7D&file=a%20new%20document%20under%20Bobbie%20Test%20Shared%20Site.docx&action=default&mobileredirect=true",
            "e_tag": None,
            "c_tag": '6""',
            "size": None,
            "created_by_type": '7""',
            "created_by_display_name": 18733,
            "created_by_email": "bobbie@thoughtlabs00.onmicrosoft.com",
            "created_by_id": "Bobbie Hawaii",
            "modified_by_display_name": "340254d6-4d75-4cb0-baf3-bcfce7ab1a56",
            "modified_by_email": "user",
            "modified_by_id": "Bobbie Hawaii",
            "file_mime_type": "document",
            "file_xor_hash": "340254d6-4d75-4cb0-baf3-bcfce7ab1a56",
            "remote_tenant_id": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "remote_site_id": "eUkIHU5FYG6AnpW6uu4HrQ6RIAA=",
            "remote_drive_id": None,
            "ms_path": "object_path_1",
            "is_internal": None,
            "created_by_domain": "thoughtlabs00.onmicrosoft.com",
            "parent_id": "01D3GIE3GV6Y2GOVW442325BZO354PWSELRRZ",
            "parent_path": "/drives/b!pKnEGmj9w0SAWDEqpTYU0JtY8iv1nQhOiF7cqt_iY-MVqLscgbIjRbBgGH7B3l62/root:/top-level-folder",
        },
        {
            "id_db": 4,
            "dt_created": "2020-12-02T23:01:16",
            "dt_modified": "2020-12-30T23:32:18",
            "ms_id": "01TMD3YV4TY2JEV4VK7ZBLT3EJ5N434E6P",
            "ms_drive_id": "fake-drive-id",
            "ms_dt_created": "2020-10-30T16:50:18",
            "ms_dt_modified": "2020-10-30T16:51:05",
            "name": "Word doc in private test site created by Lucas .docx",
            "download_url": "https://thoughtlabs00.sharepoint.com/sites/PrivateTestSiteCreatedByLucas/_layouts/15/download.aspx?UniqueId=4a92c693-aaf2-42fe-b9ec-89eb79be13cf&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdGhvdWdodGxhYnMwMC5zaGFyZXBvaW50LmNvbUAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjA5MzcxMTAyIiwiZXhwIjoiMTYwOTM3NDcwMiIsImVuZHBvaW50dXJsIjoiRmYxZG5uL1Q3YVZ2SHFYR0ttNGJ2VmltQ1o1NFlxOFhPSmFNdldMTFU0UT0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE2MCIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiWmpBNVlqZzFPRGt0TURNeVlTMDBaRFl6TFdJMlpqQXRNekF3WWpObU4yRmlNVFpqIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ik9HUTVOekV6TXpjdFlqQmxaaTAwWTJJekxXRTBabVF0TnpFd016WXdaV1UzTmpZdyIsImFwcF9kaXNwbGF5bmFtZSI6IkFsdGl0dWRlIG1zX3NjcmFwZXIgdGVzdCIsIm5hbWVpZCI6ImUwM2VmMjVkLWUxNGQtNDM0YS1hNjA5LThmODg3NGQxOTFjYkAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJyb2xlcyI6Imdyb3VwLnJlYWQgYWxsc2l0ZXMucmVhZCBhbGxmaWxlcy5yZWFkIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjEiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.UmVscTVXbmxPaURMYUtLSStib3RGVUVNTzk4bVV3TUtCM2pIZkhKWkhKND0&ApiVersion=2.0",
            "web_url": "https://thoughtlabs00.sharepoint.com/sites/PrivateTestSiteCreatedByLucas/_layouts/15/Doc.aspx?sourcedoc=%7B4A92C693-AAF2-42FE-B9EC-89EB79BE13CF%7D&file=Word%20doc%20in%20private%20test%20site%20created%20by%20Lucas%20.docx&action=default&mobileredirect=true",
            "e_tag": None,
            "c_tag": '6""',
            "size": None,
            "created_by_type": '6""',
            "created_by_display_name": 17006,
            "created_by_email": "lucas@thoughtlabs00.onmicrosoft.com",
            "created_by_id": "Lucas Gordon",
            "modified_by_display_name": "cb9548d3-89a2-4754-901f-9ee04bef60b0",
            "modified_by_email": "user",
            "modified_by_id": "Lucas Gordon",
            "file_mime_type": "document",
            "file_xor_hash": "cb9548d3-89a2-4754-901f-9ee04bef60b0",
            "remote_tenant_id": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "remote_site_id": "mrtYgiW8yKXo+7/aSPoLq4A6T44=",
            "remote_drive_id": None,
            "ms_path": "object_path_1",
            "is_internal": None,
            "created_by_domain": "thoughtlabs00.onmicrosoft.com",
            "parent_id": "01D3GIE3GV6Y2GOVW442325BZO354PWSELRRZ",
            "parent_path": "/drives/b!pKnEGmj9w0SAWDEqpTYU0JtY8iv1nQhOiF7cqt_iY-MVqLscgbIjRbBgGH7B3l62/root:/top-level-folder",
        },
        {
            "id_db": 5,
            "dt_created": "2020-12-02T23:01:16",
            "dt_modified": "2021-05-19T00:55:20",
            "ms_id": "016MCEIVFUWWODSSBS4VFIULB3J5EUDEIH",
            "ms_drive_id": "fake-drive-id",
            "ms_dt_created": "2020-10-30T19:17:26",
            "ms_dt_modified": "2020-10-30T19:18:09",
            "name": "This is a document under Bobbie Shared Test Site.docx",
            "download_url": "https://thoughtlabs00.sharepoint.com/sites/BobbieTestSharedSite/_layouts/15/download.aspx?UniqueId=399cb5b4-3248-4ae5-8a2c-3b4f49419107&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdGhvdWdodGxhYnMwMC5zaGFyZXBvaW50LmNvbUAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjIxMzg1NzE2IiwiZXhwIjoiMTYyMTM4OTMxNiIsImVuZHBvaW50dXJsIjoiczJacVhNTURhbEVzZVJDQkJjenRWaThFWkZlMlNnOTVCUEdvaTJZRXNGYz0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE0OSIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiT1RKa09UUTVNamN0TjJNMFpTMDBaakU1TFRnMVltRXRNamhtWTJGaE5tSTJOVEV4IiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ik5tTTNZbU5oTlRNdFpEUmhPUzAwWVRNNUxXSXhaR1F0Tm1ZME1tTmhNamxsTmpZNCIsImFwcF9kaXNwbGF5bmFtZSI6IkFsdGl0dWRlIG1zX3NjcmFwZXIgdGVzdCIsIm5hbWVpZCI6ImUwM2VmMjVkLWUxNGQtNDM0YS1hNjA5LThmODg3NGQxOTFjYkAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJyb2xlcyI6Imdyb3VwLnJlYWQgYWxsc2l0ZXMucmVhZCBhbGxmaWxlcy5yZWFkIGFsbHNpdGVzLmZ1bGxjb250cm9sIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjEiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.ODJHc2t4VDBTN05lS0p6R1hjbHI5NnkyaXZwMW1nYWRmMUZJOHpJcXl6ND0&ApiVersion=2.0",
            "web_url": "https://thoughtlabs00.sharepoint.com/sites/BobbieTestSharedSite/_layouts/15/Doc.aspx?sourcedoc=%7B399CB5B4-3248-4AE5-8A2C-3B4F49419107%7D&file=This%20is%20a%20document%20under%20Bobbie%20Shared%20Test%20Site.docx&action=default&mobileredirect=true",
            "e_tag": None,
            "c_tag": '6""',
            "size": None,
            "created_by_type": '7""',
            "created_by_display_name": 18739,
            "created_by_email": "bobbie@thoughtlabs00.onmicrosoft.com",
            "created_by_id": "Bobbie Hawaii",
            "modified_by_display_name": "340254d6-4d75-4cb0-baf3-bcfce7ab1a56",
            "modified_by_email": "user",
            "modified_by_id": "Bobbie Hawaii",
            "file_mime_type": "document",
            "file_xor_hash": "340254d6-4d75-4cb0-baf3-bcfce7ab1a56",
            "remote_tenant_id": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "remote_site_id": "bgISGG41lE2GxTA3PrOgU/oo2LY=",
            "remote_drive_id": None,
            "ms_path": "object_path_1",
            "is_internal": None,
            "created_by_domain": "thoughtlabs00.onmicrosoft.com",
            "parent_id": "01D3GIE3GV6Y2GOVW442325BZO354PWSELRRZ",
            "parent_path": "/drives/b!pKnEGmj9w0SAWDEqpTYU0JtY8iv1nQhOiF7cqt_iY-MVqLscgbIjRbBgGH7B3l62/root:/top-level-folder",
        },
        {
            "id_db": 6,
            "dt_created": "2021-01-02T23:01:16",
            "dt_modified": "2021-05-19T00:55:20",
            "ms_id": "01D3GIE3GV6Y2GOVW442325BZO354PWSELRRZ",
            "ms_drive_id": "fake-drive-id",
            "ms_dt_created": "2020-10-30T19:17:26",
            "ms_dt_modified": "2020-10-30T19:18:09",
            "name": "top-level-folder",
            "download_url": "https://thoughtlabs00.sharepoint.com/sites/BobbieTestSharedSite/_layouts/15/download.aspx?UniqueId=399cb5b4-3248-4ae5-8a2c-3b4f49419107&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdGhvdWdodGxhYnMwMC5zaGFyZXBvaW50LmNvbUAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjIxMzg1NzE2IiwiZXhwIjoiMTYyMTM4OTMxNiIsImVuZHBvaW50dXJsIjoiczJacVhNTURhbEVzZVJDQkJjenRWaThFWkZlMlNnOTVCUEdvaTJZRXNGYz0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE0OSIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiT1RKa09UUTVNamN0TjJNMFpTMDBaakU1TFRnMVltRXRNamhtWTJGaE5tSTJOVEV4IiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ik5tTTNZbU5oTlRNdFpEUmhPUzAwWVRNNUxXSXhaR1F0Tm1ZME1tTmhNamxsTmpZNCIsImFwcF9kaXNwbGF5bmFtZSI6IkFsdGl0dWRlIG1zX3NjcmFwZXIgdGVzdCIsIm5hbWVpZCI6ImUwM2VmMjVkLWUxNGQtNDM0YS1hNjA5LThmODg3NGQxOTFjYkAwNzg1ZmRiYS1mNDhmLTRlMjMtYmI4Mi1iNTQyMzQ3YWIyYTQiLCJyb2xlcyI6Imdyb3VwLnJlYWQgYWxsc2l0ZXMucmVhZCBhbGxmaWxlcy5yZWFkIGFsbHNpdGVzLmZ1bGxjb250cm9sIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjEiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.ODJHc2t4VDBTN05lS0p6R1hjbHI5NnkyaXZwMW1nYWRmMUZJOHpJcXl6ND0&ApiVersion=2.0",
            "web_url": "https://thoughtlabs00.sharepoint.com/sites/BobbieTestSharedSite/_layouts/15/Doc.aspx?sourcedoc=%7B399CB5B4-3248-4AE5-8A2C-3B4F49419107%7D&file=This%20is%20a%20document%20under%20Bobbie%20Shared%20Test%20Site.docx&action=default&mobileredirect=true",
            "e_tag": None,
            "c_tag": '6""',
            "size": None,
            "created_by_type": '7""',
            "created_by_display_name": 18739,
            "created_by_email": "bobbie@thoughtlabs00.onmicrosoft.com",
            "created_by_id": "Bobbie Hawaii",
            "modified_by_display_name": "340254d6-4d75-4cb0-baf3-bcfce7ab1a56",
            "modified_by_email": "user",
            "modified_by_id": "Bobbie Hawaii",
            "file_xor_hash": "340254d6-4d75-4cb0-baf3-bcfce7ab1a56",
            "remote_drive_id": None,
            "ms_path": "object_path_1",
            "is_internal": None,
            "created_by_domain": "thoughtlabs00.onmicrosoft.com",
            "parent_path": "/drives/01D3GIE3GV6Y2GOVW442325BZO354PWSELRRZ/root:",
        },
    ]


@pytest.fixture
def ms_drives_docs_permissions_data():
    return [
        {
            "id_db": 1,
            "dt_created": "2021-05-19 00:55:21",
            "dt_modified": "2021-05-19 00:55:21",
            "ms_id": "TmV3IFByaXZhdGUgVGVzdCBTaXRlIE93bmVycw",
            "ms_drive_id": "b!_eWtzjpwvUiM6mV7kFhsVS6NLmf-VBJBpp-F9caSF_O-u0FBJ1BzSZFC_OJhaaHR",
            "ms_doc_id": "012QV2V4G5OLMZRHOVGNH2VHCJ5WMYVGZ7",
            "roles": "owner",
            "has_password": None,
            "link_prevents_download": None,
            "link_scope": "organization",
            "link_type": None,
            "link_web_url": None,
            "granted_to_type": "user",
            "granted_to_display_name": "New Private Test Site Owners",
            "granted_to_email": None,
            "granted_to_id": None,
            "granted_to": None,
            "inherited_from": None,
        },
        {
            "id_db": 2,
            "dt_created": "2021-05-19 00:55:21",
            "dt_modified": "2021-05-19 00:55:21",
            "ms_id": "TmV3IFByaXZhdGUgVGVzdCBTaXRlIFZpc2l0b3Jz",
            "ms_drive_id": "b!_eWtzjpwvUiM6mV7kFhsVS6NLmf-VBJBpp-F9caSF_O-u0FBJ1BzSZFC_OJhaaHR",
            "ms_doc_id": "015XDZUDG42SYYNSTFNNBZNZYK4QAGDBJA",
            "roles": "read",
            "has_password": None,
            "link_prevents_download": None,
            "link_scope": "anonymous",
            "link_type": None,
            "link_web_url": None,
            "granted_to_type": "user",
            "granted_to_display_name": "New Private Test Site Visitors",
            "granted_to_email": None,
            "granted_to_id": None,
            "granted_to": None,
            "inherited_from": None,
        },
        {
            "id_db": 3,
            "dt_created": "2021-05-19 00:55:21",
            "dt_modified": "2021-05-19 00:55:21",
            "ms_id": "TmV3IFByaXZhdGUgVGVzdCBTaXRlIE1lbWJlcnM",
            "ms_drive_id": "015XDZUDBNXD3NQIBXRFGLUHMWKBV3NUJP",
            "ms_doc_id": "012QV2V4G5OLMZRHOVGNH2VHCJ5WMYVGZ7",
            "roles": "write",
            "has_password": None,
            "link_prevents_download": None,
            "link_scope": "anonymous",
            "link_type": None,
            "link_web_url": None,
            "granted_to_type": "user",
            "granted_to_display_name": "New Private Test Site Members",
            "granted_to_email": None,
            "granted_to_id": None,
            "granted_to": None,
            "inherited_from": None,
        },
        {
            "id_db": 4,
            "dt_created": "2021-05-19 00:55:21",
            "dt_modified": "2021-05-19 00:55:21",
            "ms_id": "Yzowby5jfGZlZGVyYXRlZGRpcmVjdG9yeWNsYWltcHJvdmlkZXJ8YWExYzlhNmMtMWQ0Zi00YWUyLThjOWMtODBkMDhhNDgyMjJkX28",
            "ms_drive_id": "015XDZUDBNXD3NQIBXRFGLUHMWKBV3NUJP",
            "ms_doc_id": "012QV2V4G5OLMZRHOVGNH2VHCJ5WMYVGZ7",
            "roles": "owner",
            "has_password": None,
            "link_prevents_download": None,
            "link_scope": "organization",
            "link_type": None,
            "link_web_url": None,
            "granted_to_type": "user",
            "granted_to_display_name": "New Private Test Site Owners",
            "granted_to_email": "NewPrivateTestSite@thoughtlabs00.onmicrosoft.com",
            "granted_to_id": "aa1c9a6c-1d4f-4ae2-8c9c-80d08a48222d",
            "granted_to": None,
            "inherited_from": None,
        },
        {
            "id_db": 5,
            "dt_created": "2021-05-19 00:55:21",
            "dt_modified": "2021-05-19 00:55:21",
            "ms_id": "QW1pciBUZXN0IFNoYXJlZCBTaXRlIE93bmVycw",
            "ms_drive_id": "fake-drive-id",
            "ms_doc_id": "016MCEIVFUWWODSSBS4VFIULB3J5EUDEIH",
            "roles": "owner",
            "has_password": None,
            "link_prevents_download": None,
            "link_scope": None,
            "link_type": None,
            "link_web_url": None,
            "granted_to_type": "user",
            "granted_to_display_name": "Amir Test Shared Site Owners",
            "granted_to_email": None,
            "granted_to_id": None,
            "granted_to": None,
            "inherited_from": None,
        },
        {
            "id_db": 6,
            "dt_created": "2021-05-19 00:55:21",
            "dt_modified": "2021-05-19 00:55:21",
            "ms_id": "QW1pciBUZXN0IFNoYXJlZCBTaXRlIFZpc2l0b3Jz",
            "ms_drive_id": "fake-drive-id",
            "ms_doc_id": "016MCEIVFUWWODSSBS4VFIULB3J5EUDEIH",
            "roles": "read",
            "has_password": None,
            "link_prevents_download": None,
            "link_scope": "anonymous",
            "link_type": None,
            "link_web_url": None,
            "granted_to_type": "user",
            "granted_to_display_name": "Amir Test Shared Site Visitors",
            "granted_to_email": None,
            "granted_to_id": None,
            "granted_to": None,
            "inherited_from": None,
        },
        {
            "id_db": 7,
            "dt_created": "2021-05-19 00:55:21",
            "dt_modified": "2021-05-19 00:55:21",
            "ms_id": "QW1pciBUZXN0IFNoYXJlZCBTaXRlIE1lbWJlcnM",
            "ms_drive_id": "fake-drive-id",
            "ms_doc_id": "016MCEIVFUWWODSSBS4VFIULB3J5EUDEIH",
            "roles": "write",
            "has_password": None,
            "link_prevents_download": None,
            "link_scope": "anonymous",
            "link_type": None,
            "link_web_url": None,
            "granted_to_type": "user",
            "granted_to_display_name": "Amir Test Shared Site Members",
            "granted_to_email": None,
            "granted_to_id": None,
            "granted_to": None,
            "inherited_from": None,
        },
        {
            "id_db": 8,
            "dt_created": "2021-05-19 00:55:21",
            "dt_modified": "2021-05-19 00:55:21",
            "ms_id": "Yzowby5jfGZlZGVyYXRlZGRpcmVjdG9yeWNsYWltcHJvdmlkZXJ8NjRkYTZlMTUtNDJkNC00YTk0LTk3M2ItNTNjYjAxNmJhZDJmX28",
            "ms_drive_id": "fake-drive-id",
            "ms_doc_id": "016MCEIVFUWWODSSBS4VFIULB3J5EUDEIH",
            "roles": "owner",
            "has_password": None,
            "link_prevents_download": None,
            "link_scope": None,
            "link_type": None,
            "link_web_url": None,
            "granted_to_type": "user",
            "granted_to_display_name": "Amir Test Shared Site Owners",
            "granted_to_email": "AmirTestSharedSite@thoughtlabs00.onmicrosoft.com",
            "granted_to_id": "64da6e15-42d4-4a94-973b-53cb016bad2f",
            "granted_to": None,
            "inherited_from": None,
        },
        {
            "id_db": 9,
            "dt_created": "2021-05-19 00:55:21",
            "dt_modified": "2021-05-19 00:55:21",
            "ms_id": "aTowIy5mfG1lbWJlcnNoaXB8cHVsa2l0QHRob3VnaHRsYWJzMDAub25taWNyb3NvZnQuY29t",
            "ms_drive_id": "fake-drive-id",
            "ms_doc_id": "015XDZUDAOUU7SDEIJMRGKBCZJERJIPG4Y",
            "roles": "owner",
            "has_password": None,
            "link_prevents_download": None,
            "link_scope": None,
            "link_type": None,
            "link_web_url": None,
            "granted_to_type": "user",
            "granted_to_display_name": "Pulkit Khetrapal",
            "granted_to_email": "pulkit@thoughtlabs00.onmicrosoft.com",
            "granted_to_id": "79c2e5fd-cab9-4a42-a045-ba8d7b1fc612",
            "granted_to": None,
            "inherited_from": None,
        },
    ]


@pytest.fixture
def ms_groups():
    return []


@pytest.fixture
def ms_sites_drives_data():
    return [
        {"ms_id": "fake-drive-id", "web_url": "drive_web_url_1"},
    ]


@pytest.fixture
def ms_users_data():
    return []
