name: Code style & unit tests

"on":
  push:
    branches-ignore:
      - master
      - release/*

    paths-ignore:
      - docs/**
      - external_api/version.txt
      - CHANGELOG.md
      - README.md
  workflow_dispatch: {}

jobs:
  code_style:
    name: Code style
    runs-on: ubuntu-latest
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
      PYTHONUSERBASE: "${{ github.workspace }}/.cache/py-user-base"

    # To add custom steps to this workflow, start step name with `Custom: `
    # To override existing step, set name to `Custom: <original_step_name>`
    steps:
      - name: Add PYTHONUSERBASE to PATH
        id: add-pythonuserbase
        run: |
          echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache Python site-packages
        uses: actions/cache@v2
        with:
          path: "${{ env.PYTHONUSERBASE }}"
          key: "${{ runner.os }}-3.7-full-${{ env.CACHE_KEY }}-${{ hashFiles('./Pipfile.lock') }}"
          restore-keys: |
            ${{ runner.os }}-3.7-full-${{ env.CACHE_KEY }}-
      - name: Install package dependencies
        env:
          INTERNAL_PYPI_USERNAME: "${{ secrets.INTERNAL_PYPI_USERNAME }}"
          INTERNAL_PYPI_PASS: "${{ secrets.INTERNAL_PYPI_PASS }}"
          INTERNAL_PYPI_URL: "${{ secrets.INTERNAL_PYPI_URL }}"
        run: |
          python -m pip install -i https://${INTERNAL_PYPI_USERNAME}:${INTERNAL_PYPI_PASS}@${INTERNAL_PYPI_URL} -U github_actions_script
          python -m github_actions_script install_dev -d
          pre_commit --install --preset ci -d
      - name: Pre-commit checks
        run: |
          pre_commit -d --preset ci

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
      PYTHONUSERBASE: "${{ github.workspace }}/.cache/py-user-base"

    # To add custom steps to this workflow, start step name with `Custom: `
    # To override existing step, set name to `Custom: <original_step_name>`
    steps:
      - name: Add PYTHONUSERBASE to PATH
        id: add-pythonuserbase
        run: |
          echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache Python site-packages
        uses: actions/cache@v2
        with:
          path: "${{ env.PYTHONUSERBASE }}"
          key: "${{ runner.os }}-3.7-full-${{ env.CACHE_KEY }}-${{ hashFiles('./Pipfile.lock') }}"
          restore-keys: |
            ${{ runner.os }}-3.7-full-${{ env.CACHE_KEY }}-
      - name: Install package dependencies
        env:
          INTERNAL_PYPI_USERNAME: "${{ secrets.INTERNAL_PYPI_USERNAME }}"
          INTERNAL_PYPI_PASS: "${{ secrets.INTERNAL_PYPI_PASS }}"
          INTERNAL_PYPI_URL: "${{ secrets.INTERNAL_PYPI_URL }}"
        run: |
          python -m pip install -i https://${INTERNAL_PYPI_USERNAME}:${INTERNAL_PYPI_PASS}@${INTERNAL_PYPI_URL} -U github_actions_script
          python -m github_actions_script install_dev -d
          pre_commit --install --check pytest pytest-cov -d
      - name: Unit tests
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID_DEV }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}"
          ENV: dev
          AWS_REGION: us-west-2
          AWS_DEFAULT_REGION: us-west-2
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        run: |
          [ ! -d "tests" ] && echo "tests directory not found, skipping"
          [ ! -d "tests" ] && exit
          pre_commit -d --check pytest-cov
          [ -z "$CODECOV_TOKEN" ] && echo "CODECOV_TOKEN is not set, skipping"
          [ -z "$CODECOV_TOKEN" ] && exit
          python -m codecov
