type: lambda
runtime: python3.7
function_name: &func_name altitude-{{ENV}}-lambda-delete-permissions-by-risk-id-{{SUFFIX}}
iam_role: arn:aws:iam::{{AWS_ACCOUNT}}:role/altitude-{{ENV}}-lambda-execution-frontend-role
handler: services.delete_permissions_by_risk_id.delete_permissions_by_risk_id_handler.main_handler
description: External API service to delete Permission Ids by risk id
use_vpc: True
memory_size: 1728
timeout: 30
tracing_config_mode: Active
notification_email: devops@altitudenetworks.com
log_group_subscriptions:
  - filter_name: log-dna
    destination_arn: {{ENV_CONFIG.logdna_destination_arn}}
environment:
  {% set DEBUG_MODE = "true" if ENV == "dev" else "false" %}
  DEBUG_MODE: '{{DEBUG_MODE}}'
triggers:
  - type: apigateway
    name: flavius-{{ENV}}-{{SUFFIX}}
    path: /risk/{riskId}/permissions
    method: delete
    function_name: *func_name
    function_alias: {{ENV}}
    authorization_required: True
    application_role: FlaviusAPI
