type: lambda
runtime: python3.7
function_name: altitude-{{ENV}}-lambda-update-risk-status-{{SUFFIX}}
handler: services.update_risk_status.update_risk_status_handler.main_handler
iam_role: arn:aws:iam::{{AWS_ACCOUNT}}:role/altitude-{{ENV}}-lambda-execution-frontend-role
description: External API service to update risk id status in top risks table
use_vpc: True
memory_size: 1728
timeout: &timeout 900
tracing_config_mode: Active
notification_email: devops@altitudenetworks.com
log_group_subscriptions:
  - filter_name: log-dna
    destination_arn: {{ENV_CONFIG.logdna_destination_arn}}
environment:
  {% set DEBUG_MODE = "true" if ENV == "dev" else "false" %}
  DEBUG_MODE: '{{DEBUG_MODE}}'
triggers:
  {% for PROJECT_CONFIG in PROJECT_CONFIGS %}
  - type: sqs
    name: {{PROJECT_CONFIG.project_name}}-{{ENV}}-update-risk-status-{{SUFFIX}}
    max_message_size: 262144
    message_retention_period: 1209600
    visibility_timeout: *timeout
    kms_key_id: {{PROJECT_CONFIG.kms_key_id}}
    dlq:
      name: {{PROJECT_CONFIG.project_name}}-{{ENV}}-update-risk-status-{{SUFFIX}}-dlq
      max_receive_count: 1
    tags:
      Project: {{PROJECT_CONFIG.project_name}}
  {% endfor %}
